/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package controle;

/**
 *
 * @author Koragem
 */

import conexao.Conexao;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;

public class frmTela extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmTela.class.getName());

    /**
     * Creates new form frmTela
     */
    
    Conexao con_cliente; // Declara o objeto da conexão
    
    public frmTela() {
        initComponents();
        con_cliente = new Conexao(); // Inicializa o objeto
        con_cliente.conecta();
        con_cliente.executaSQL("select * from tbclientes order by cod");
        preencherTabela();// Chama o método que conecta ao banco
        posicionarRegistro();
        tblClientes.setAutoCreateRowSorter(true);// ativa a classificação ordenada da tabela
        
        this.getContentPane().setBackground(new java.awt.Color(248, 246, 240));
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        txtNasc = new javax.swing.JTextField();
        txtFone = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtCod = new javax.swing.JTextField();
        PrimeiroRegistro = new javax.swing.JButton();
        VoltarUmRegistro = new javax.swing.JButton();
        AvancarUmRegistro = new javax.swing.JButton();
        UltimoRegistro = new javax.swing.JButton();
        BtnNovo = new javax.swing.JButton();
        BtnCadastrar = new javax.swing.JButton();
        BtnAlterar = new javax.swing.JButton();
        BtnExcluir = new javax.swing.JButton();
        txtPesquisar = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(27, 94, 32));
        jLabel1.setText("Código:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(27, 94, 32));
        jLabel2.setText("Nome:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(27, 94, 32));
        jLabel3.setText("Data de Nascimento:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(27, 94, 32));
        jLabel4.setText("Telefone:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(27, 94, 32));
        jLabel5.setText("Email:");

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código", "Nome", "Data de Nascimento", "Telefone", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblClientesMouseClicked(evt);
            }
        });
        tblClientes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblClientesKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblClientes);

        txtNasc.setForeground(new java.awt.Color(186, 90, 90));

        txtFone.setForeground(new java.awt.Color(186, 90, 90));

        txtEmail.setForeground(new java.awt.Color(186, 90, 90));
        txtEmail.addActionListener(this::txtEmailActionPerformed);

        txtNome.setForeground(new java.awt.Color(186, 90, 90));

        txtCod.setForeground(new java.awt.Color(186, 90, 90));
        txtCod.addActionListener(this::txtCodActionPerformed);

        PrimeiroRegistro.setBackground(new java.awt.Color(186, 90, 90));
        PrimeiroRegistro.setText("⏮");
        PrimeiroRegistro.addActionListener(this::PrimeiroRegistroActionPerformed);

        VoltarUmRegistro.setBackground(new java.awt.Color(186, 90, 90));
        VoltarUmRegistro.setText("◀");
        VoltarUmRegistro.addActionListener(this::VoltarUmRegistroActionPerformed);

        AvancarUmRegistro.setBackground(new java.awt.Color(186, 90, 90));
        AvancarUmRegistro.setText("▶");
        AvancarUmRegistro.addActionListener(this::AvancarUmRegistroActionPerformed);

        UltimoRegistro.setBackground(new java.awt.Color(186, 90, 90));
        UltimoRegistro.setText("⏭");
        UltimoRegistro.addActionListener(this::UltimoRegistroActionPerformed);

        BtnNovo.setBackground(new java.awt.Color(186, 90, 90));
        BtnNovo.setText("+");
        BtnNovo.addActionListener(this::BtnNovoActionPerformed);

        BtnCadastrar.setBackground(new java.awt.Color(186, 90, 90));
        BtnCadastrar.setText("🖫");
        BtnCadastrar.addActionListener(this::BtnCadastrarActionPerformed);

        BtnAlterar.setBackground(new java.awt.Color(186, 90, 90));
        BtnAlterar.setText("📝");
        BtnAlterar.addActionListener(this::BtnAlterarActionPerformed);

        BtnExcluir.setBackground(new java.awt.Color(186, 90, 90));
        BtnExcluir.setText("-");
        BtnExcluir.addActionListener(this::BtnExcluirActionPerformed);

        txtPesquisar.setForeground(new java.awt.Color(186, 90, 90));
        txtPesquisar.setText("Pesquisar");

        btnPesquisar.setBackground(new java.awt.Color(186, 90, 90));
        btnPesquisar.setText("🔍");
        btnPesquisar.addActionListener(this::btnPesquisarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCod)
                    .addComponent(txtNome)
                    .addComponent(txtNasc)
                    .addComponent(txtFone)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PrimeiroRegistro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(VoltarUmRegistro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AvancarUmRegistro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UltimoRegistro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnCadastrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnExcluir))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtPesquisar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPesquisar)
                        .addGap(419, 419, 419)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisar))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(txtCod, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtFone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PrimeiroRegistro)
                    .addComponent(VoltarUmRegistro)
                    .addComponent(AvancarUmRegistro)
                    .addComponent(UltimoRegistro)
                    .addComponent(BtnCadastrar)
                    .addComponent(BtnNovo)
                    .addComponent(BtnAlterar)
                    .addComponent(BtnExcluir))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void tblClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblClientesMouseClicked
        int linha_selecionada = tblClientes.getSelectedRow();
    
        txtCod.setText(tblClientes.getValueAt(linha_selecionada, 0).toString());
        txtNome.setText(tblClientes.getValueAt(linha_selecionada, 1).toString());
        txtNasc.setText(tblClientes.getValueAt(linha_selecionada, 2).toString());
        txtFone.setText(tblClientes.getValueAt(linha_selecionada, 3).toString());
        txtEmail.setText(tblClientes.getValueAt(linha_selecionada, 4).toString());
    }//GEN-LAST:event_tblClientesMouseClicked

    private void tblClientesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblClientesKeyPressed
        int linha_selecionada = tblClientes.getSelectedRow();
    
        txtCod.setText(tblClientes.getValueAt(linha_selecionada, 0).toString());
        txtNome.setText(tblClientes.getValueAt(linha_selecionada, 1).toString());
        txtNasc.setText(tblClientes.getValueAt(linha_selecionada, 2).toString());
        txtFone.setText(tblClientes.getValueAt(linha_selecionada, 3).toString());
        txtEmail.setText(tblClientes.getValueAt(linha_selecionada, 4).toString());
    }//GEN-LAST:event_tblClientesKeyPressed

    private void VoltarUmRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarUmRegistroActionPerformed
        try {
        con_cliente.resultset.previous();
        mostrar_Dados();
    } catch (SQLException erro) {
        JOptionPane.showMessageDialog(null, "Não foi possível acessar o registro anterior: " + erro);
    }
    }//GEN-LAST:event_VoltarUmRegistroActionPerformed

    private void UltimoRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UltimoRegistroActionPerformed
        try {
        con_cliente.resultset.last();
        mostrar_Dados();
    } catch (SQLException erro) {
        JOptionPane.showMessageDialog(null, "Não foi possível acessar o próximo registro: " + erro);
    }
    }//GEN-LAST:event_UltimoRegistroActionPerformed

    private void PrimeiroRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrimeiroRegistroActionPerformed
        try {
        con_cliente.resultset.first();
        mostrar_Dados();
    } catch (SQLException erro) {
        JOptionPane.showMessageDialog(null, "Não foi possível acessar o primeiro registro: " + erro);
    }
    }//GEN-LAST:event_PrimeiroRegistroActionPerformed

    private void AvancarUmRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AvancarUmRegistroActionPerformed
        try {
        con_cliente.resultset.next();
        mostrar_Dados();
    } catch (SQLException erro) {
        JOptionPane.showMessageDialog(null, "Não foi possível acessar o próximo registro: " + erro);
    }
    }//GEN-LAST:event_AvancarUmRegistroActionPerformed

    private void BtnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNovoActionPerformed
        txtCod.setText("");
        txtNome.setText("");
        txtNasc.setText("");
        txtFone.setText("");
        txtEmail.setText("");
        txtCod.requestFocus(); // Coloca o cursor no campo código
    }//GEN-LAST:event_BtnNovoActionPerformed

    private void BtnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCadastrarActionPerformed
        String nome = txtNome.getText();
        String data_nasc = txtNasc.getText();
        String telefone = txtFone.getText();
        String email = txtEmail.getText();
    
    try {
        String insert_sql = "insert into tbclientes (nome, dt_nasc, telefone, email) values ('" 
                            + nome + "','" + data_nasc + "','" + telefone + "','" + email + "')";
        
        con_cliente.statement.executeUpdate(insert_sql);
        JOptionPane.showMessageDialog(null, "Gravação realizada com sucesso!", "Mensagem do Programa", JOptionPane.INFORMATION_MESSAGE);
        
        // Atualiza a tabela na tela
        con_cliente.executaSQL("select * from tbclientes order by cod");
        preencherTabela();
        
    } catch (SQLException errosql) {
        JOptionPane.showMessageDialog(null, "\n Erro na gravação: " + errosql, "Mensagem do Programa", JOptionPane.INFORMATION_MESSAGE);
    }
    }//GEN-LAST:event_BtnCadastrarActionPerformed

    private void BtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAlterarActionPerformed
        String nome = txtNome.getText();
        String data_nasc = txtNasc.getText();
        String telefone = txtFone.getText();
        String email = txtEmail.getText();
        String sql;
        String msg = "";
    
    try {
        if (txtCod.getText().equals("")) {
            sql = "insert into tbclientes (nome, dt_nasc, telefone, email) values ('" 
                  + nome + "','" + data_nasc + "','" + telefone + "','" + email + "')";
            msg = "Gravação de um novo registro";
        } else {
            sql = "update tbclientes set nome='" + nome + "', dt_nasc='" + data_nasc 
                  + "', telefone='" + telefone + "', email='" + email + "' where cod = " + txtCod.getText();
            msg = "Alteração de registro";
        }
        
        con_cliente.statement.executeUpdate(sql);
        JOptionPane.showMessageDialog(null, msg + " realizada com sucesso!", "Mensagem do Programa", JOptionPane.INFORMATION_MESSAGE);
        
        con_cliente.executaSQL("select * from tbclientes order by cod");
        preencherTabela();
        
    } catch (SQLException errosql) {
        JOptionPane.showMessageDialog(null, "\n Erro na alteração: " + errosql, "Mensagem do Programa", JOptionPane.INFORMATION_MESSAGE);
    }
    }//GEN-LAST:event_BtnAlterarActionPerformed

    private void BtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExcluirActionPerformed
        String sql = "";
    try {
        int resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja excluir o registro?", "Confirmar Exclusão", JOptionPane.YES_NO_OPTION);
        
        if (resposta == JOptionPane.YES_OPTION) {
            sql = "delete from tbclientes where cod = " + txtCod.getText();
            int excluiu = con_cliente.statement.executeUpdate(sql);
            
            if (excluiu == 1) {
                JOptionPane.showMessageDialog(null, "Exclusão realizada com sucesso!", "Mensagem do Programa", JOptionPane.INFORMATION_MESSAGE);
                con_cliente.executaSQL("select * from tbclientes order by cod");
                preencherTabela();
                posicionarRegistro();
            } else {
                JOptionPane.showMessageDialog(null, "Operação cancelada pelo usuário!", "Mensagem do Programa", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    } catch (SQLException errosql) {
        JOptionPane.showMessageDialog(null, "Erro na exclusão: " + errosql, "Mensagem do Programa", JOptionPane.INFORMATION_MESSAGE);
    }
    }//GEN-LAST:event_BtnExcluirActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        try {
        // Busca os registros que começam com o texto digitado no txtPesquisar
        String pesquisa = "select * from tbclientes where nome like '" + txtPesquisar.getText() + "%'";
        
        con_cliente.executaSQL(pesquisa);
        
        // Se encontrar pelo menos um registro
        if (con_cliente.resultset.first()) {
            preencherTabela(); // Atualiza a JTable com o resultado da pesquisa
        } else {
            JOptionPane.showMessageDialog(null, "\n Não existem dados com este parâmetro!", "Mensagem do Programa", JOptionPane.INFORMATION_MESSAGE);
        }
    } catch (SQLException errosql) {
        JOptionPane.showMessageDialog(null, "\n Os dados digitados não foram localizados: " + errosql, "Mensagem do Programa", JOptionPane.INFORMATION_MESSAGE);
    }
    }//GEN-LAST:event_btnPesquisarActionPerformed
    
    public void preencherTabela(){
    tblClientes.getColumnModel().getColumn(0).setPreferredWidth(4);
    tblClientes.getColumnModel().getColumn(1).setPreferredWidth(150);
    tblClientes.getColumnModel().getColumn(2).setPreferredWidth(11);
    tblClientes.getColumnModel().getColumn(3).setPreferredWidth(14);
    tblClientes.getColumnModel().getColumn(4).setPreferredWidth(100);
    
    DefaultTableModel modelo = (DefaultTableModel) tblClientes.getModel();
    modelo.setNumRows(0);
    try{
       con_cliente.resultset.beforeFirst();
       while(con_cliente.resultset.next()){
          modelo.addRow(new Object[]{
              con_cliente.resultset.getString("cod"),
              con_cliente.resultset.getString("nome"),
              con_cliente.resultset.getString("dt_nasc"),
              con_cliente.resultset.getString("telefone"),
              con_cliente.resultset.getString("email") 
          });
       }
    }catch (SQLException erro) {
        JOptionPane.showMessageDialog(null, "Erro ao listar tabela: " + erro);
    }
    
    }
    
    public void posicionarRegistro() {
    try {
        con_cliente.resultset.first(); // posiciona no 1º registro da tabela
        mostrar_Dados(); // chama o método que irá buscar o dado da tabela
    } catch(SQLException erro) {
        JOptionPane.showMessageDialog(null, "Não foi possível posicionar no primeiro registro: " + erro, "Mensagem do Programa", JOptionPane.INFORMATION_MESSAGE);
    }
}

    public void mostrar_Dados() {
    try {
        txtCod.setText(con_cliente.resultset.getString("cod")); // Associar a caixa de texto ao campo cod
        txtNome.setText(con_cliente.resultset.getString("nome")); // Associar a caixa de texto ao campo nome
        txtNasc.setText(con_cliente.resultset.getString("dt_nasc"));
        txtFone.setText(con_cliente.resultset.getString("telefone"));
        txtEmail.setText(con_cliente.resultset.getString("email"));
    } catch(SQLException erro) {
        JOptionPane.showMessageDialog(null, "Não localizou dados: " + erro, "Mensagem do Programa", JOptionPane.INFORMATION_MESSAGE);
    }
}


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmTela().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AvancarUmRegistro;
    private javax.swing.JButton BtnAlterar;
    private javax.swing.JButton BtnCadastrar;
    private javax.swing.JButton BtnExcluir;
    private javax.swing.JButton BtnNovo;
    private javax.swing.JButton PrimeiroRegistro;
    private javax.swing.JButton UltimoRegistro;
    private javax.swing.JButton VoltarUmRegistro;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblClientes;
    private javax.swing.JTextField txtCod;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFone;
    private javax.swing.JTextField txtNasc;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPesquisar;
    // End of variables declaration//GEN-END:variables
}
